### ISSUE TITLE
Geocoding fails when using non default user meta data - because it's not yet set in the database? 

### ISSUE THREAD

**Issue by aquiferweb** [strangerstudios/pmpro-membership-maps#29]
**Describe the bug**
When using the code recipe here https://www.paidmembershipspro.com/how-to-geocode-address-fields-during-checkout/ to modify which address fields are used to generate the map, the plugin fails with INVALID_REQUEST: Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter. This appears to happen because the required user meta data has not been set in the database at this point.

**To Reproduce**
Install Plugin
Add code recipe as follows:
`function pp_custom_address_fields( $member_address, $user_id, $morder ){

	$member_address = array(
		'street' 	=> get_user_meta( $user_id, 'churchname', true ),
		'city' 		=> get_user_meta( $user_id, 'parishname', true ),
		'zip' 		=> get_user_meta( $user_id, 'church_postcode', true )
	);
	
	return $member_address;
}
add_filter( 'pmpromm_member_address_after_checkout', 'pp_custom_address_fields', 10, 3 );`

Where churchname, parishname and church_postcode are extra fields set in the PMPro Register Helper, collected on the checkout page

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**
I would expect the filter to be called at a point during checkout process when the user data has been added to the database and can be accessed by the code recipe above.

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
5.6
PMPro 2.5.4
PMPro Membership Maps 0.2

</details>

**Comment by bluesteamhost** [comment]
I'm having this issue as well now. How did you resolve it? Did you resolve it??

**Comment by JarrydLong** [comment]
Thank you for bringing this to our attention. This should do the trick: 

https://gist.github.com/JarrydLong/1e1d9d042b64317e3bef6fdccd04dcc3

You'll need to change the street_name and other fields to your custom field names for this to work.

**Comment by aquiferweb** [comment]
@JarrydLong OK - if I understand correctly it uses the user_meta to populate the 'member_address' for geocoding, unless the user_meta data is empty, in which case it uses the $_REQUEST array to get the data. 
Is the priority change from 10 to 30 significant?

@bluesteamhost looks like this should help https://gist.github.com/JarrydLong/1e1d9d042b64317e3bef6fdccd04dcc3

Tim

**Comment by bluesteamhost** [comment]
@aquiferweb thanks. Yes I have already tested it and it is working.
