### ISSUE TITLE
Enhancement: Add support for Map Styles

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-membership-maps#35]
**Is your feature request related to a problem? Please describe.**
There's no way to apply a Google Map Style at the moment. 

**Describe the solution you'd like**
Add in the ability to add in a Map Style. This can be done with a filter. 

**Describe alternatives you've considered**
Add in a filter to add styling to a map.

**Additional context**
Google Maps docs here: https://developers.google.com/maps/documentation/javascript/examples/style-array

**Comment by wolvyreen** [comment]
Would love this feature.  Thanks for the consideration Jarryd :-D
