### ISSUE TITLE
When adding custom "fields" to the shortcode, if field is empty, should not show label in info Window

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-membership-maps#44]
**Describe the bug**
When adding fields to the map or directory shortcode: `fields="Label,customkey;Label2,anotherkey;"
If there is no data for custom fields do not show label in the info window.  This is how the directory/profile pages work.

Can appear sporadic. If the field is new and user has not had the opportunity to complete it, no label will show.
After the field is added, when the user or admin saves profile, then the label will show with no content.

**To Reproduce**
Add custom fields with RH
Users who update their profile, but do not complete fields.
The label will show even if there is no meta content for that user.

Should check if meta_field is not empty, to print label.
if(is_array($meta_field) && !empty($meta_field['filename']) 

**Screenshots**

<img width="345" alt="Screen Shot 2021-10-05 at 3 13 21 PM" src="https://user-images.githubusercontent.com/8083630/136089261-0f3520f4-9994-46b7-b651-57ccbe638c68.png">
**Expected behavior**
If the custom fields are blank, the LABEL should not appear (like in directory and profile shortcode)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by JarrydLong** [comment]
This issue has been resolved following updates to Membership Directory v1.2 and Membership Maps 0.3
