### ISSUE TITLE
pmpromm_override_first_marker can not be set to true

### ISSUE THREAD

**Issue by DannyCooper** [strangerstudios/pmpro-membership-maps#46]
https://github.com/strangerstudios/pmpro-membership-maps/blob/70adf81a8a4751a171bd9e1985e5eec0aa13b187/pmpro-membership-maps.php#L75-L83

I'm try to set override_first_marker_location to true in this way:

`add_filter( 'pmpromm_override_first_marker', '__return_true' );`

But when it's localized it gets converted into "1" or "true" which fails the strict comparison (===).

https://github.com/strangerstudios/pmpro-membership-maps/blob/70adf81a8a4751a171bd9e1985e5eec0aa13b187/js/user.js#L10

**Comment by JarrydLong** [comment]
This has been fixed and is available and working in V 0.3
