### ISSUE TITLE
Email address label is in English instead of French

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-membership-maps#61]
**Describe the bug**
When you open a pop-up, the email address label is in English instead of French.

**To Reproduce**
1. Go to map
2. Click on a point of the map
3. See the **Email Address** label

**Screenshots**
![image](https://user-images.githubusercontent.com/4752949/189393725-e5764fbe-fd7a-4dbc-8c15-f21685d4484c.png)  

**Expected behavior**
French translation should be shown

This came up in ticket 445139: 
>I also notice another problem with the label before the email address which is in English while the rest is in French.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.9.4, WordPress 6.0.2, PHP 7.4.30
```
</details>

**Comment by dparker1005** [comment]
That text should be able to be translated using the steps in this article: https://www.paidmembershipspro.com/translate-text-loco-translate/

**Comment by andrewlimaza** [comment]
I'm going to close this, checking the code the "Email Address" is translatable. This could have been missing a translation in the translation plugin that the customer was using.
